<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

use Faker\Factory as Faker;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //Empty the table first
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        Product::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        // Utiliser la bibliothèque Faker pour générer des données aléatoires
        $faker = Faker::create();
        $products = [
            [
                'name' => 'Goku n°615',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf', 'Parfait', 'Très bon', 'Bon', 'Moyen', 'Mauvais', 'Très Mauvais']),
                'image' => 'images/2.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Goku Kamehameha n°642',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf', 'Parfait', 'Très bon', 'Bon', 'Moyen', 'Mauvais', 'Très Mauvais']),
                'image' => 'images/3.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Super sayan Goku n°14',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf', 'Parfait', 'Très bon', 'Bon', 'Moyen', 'Mauvais', 'Très Mauvais']),
                'image' => 'images/4.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ], [
                'name' => 'Super sayan Goku first apparance n°860',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 4,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf', 'Parfait', 'Très bon', 'Bon', 'Moyen', 'Mauvais', 'Très Mauvais']),
                'image' => 'images/1.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Super sayan Goku with kamehameha n°948',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 20,
                'quantity' => 1,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf', 'Parfait', 'Très bon', 'Bon', 'Moyen', 'Mauvais', 'Très Mauvais']),
                'image' => 'images/5.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Goku ultra instinct sign n°1232',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 18,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf', 'Parfait', 'Très bon', 'Bon', 'Moyen', 'Mauvais', 'Très Mauvais']),
                'image' => 'images/6.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Goku ultra instinct n°386',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => $faker->numberBetween(1, 10),
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf', 'Parfait', 'Très bon', 'Bon', 'Moyen', 'Mauvais', 'Très Mauvais']),
                'image' => 'images/7.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Goku black n°314',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 1,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf', 'Parfait', 'Très bon', 'Bon', 'Moyen', 'Mauvais', 'Très Mauvais']),
                'image' => 'images/8.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Raditz n°616',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 1,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf', 'Parfait', 'Très bon', 'Bon', 'Moyen', 'Mauvais', 'Très Mauvais']),
                'image' => 'images/9.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Prince Vegeta n°863',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf', 'Parfait', 'Très bon', 'Bon', 'Moyen', 'Mauvais', 'Très Mauvais']),
                'image' => 'images/10.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Vegeta n°614',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf', 'Parfait', 'Très bon', 'Bon', 'Moyen', 'Mauvais', 'Très Mauvais']),
                'image' => 'images/11.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Nappa n°613',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf', 'Parfait', 'Très bon', 'Bon', 'Moyen', 'Mauvais', 'Très Mauvais']),
                'image' => 'images/12.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Vegeta n°10',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf', 'Parfait', 'Très bon', 'Bon', 'Moyen', 'Mauvais', 'Très Mauvais']),
                'image' => 'images/13.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Android 16 n°708',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf', 'Parfait', 'Très bon', 'Bon', 'Moyen', 'Mauvais', 'Très Mauvais']),
                'image' => 'images/14.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Gohan n°813',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf', 'Parfait', 'Très bon', 'Bon', 'Moyen', 'Mauvais', 'Très Mauvais']),
                'image' => 'images/15.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Master Roshi n°382',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf', 'Parfait', 'Très bon', 'Bon', 'Moyen', 'Mauvais', 'Très Mauvais']),
                'image' => 'images/16.jpg',
                'type_transaction' => $faker->randomElement(['Vente', 'Echange']),
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Silent Hill',
                'description' => 'Silent Hill est un jeu vidéo de type survival horror développé par Konami CE Tokyo et édité par Konami en 1999 sur PlayStation. Réputé pour avoir révolutionné le jeu d\'horreur par son approche psychologique de la peur, le titre de Keiichiro Toyama a connu un succès international.',
                'price' => 75,
                'quantity' => 2,
                'edition' => 'Konami',
                'weight' => 347,
                'user_id' => 1,
                'type_id' => 2,
                'condition' => $faker->randomElement(['Neuf', 'Parfait', 'Très bon', 'Bon', 'Moyen', 'Mauvais', 'Très Mauvais']),
                'image' => 'images/17.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
        ];
        DB::table('products')->insert($products);
    }
}
