<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

use Faker\Factory as Faker;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //Empty the table first
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        Product::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        // Utiliser la bibliothèque Faker pour générer des données aléatoires
        $faker = Faker::create();
        $products = [
            [
                'name' => 'Goku n°615',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/2.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Goku Kamehameha n°642',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/3.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Super sayan Goku n°14',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/4.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ], [
                'name' => 'Super sayan Goku first apparance n°860',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 4,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/1.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Super sayan Goku with kamehameha n°948',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 20,
                'quantity' => 1,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/5.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Goku ultra instinct sign n°1232',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 18,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/6.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Goku ultra instinct n°386',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => $faker->numberBetween(1, 10),
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/7.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Goku black n°314',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 1,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/8.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Raditz n°616',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 1,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/9.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Prince Vegeta n°863',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/10.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Vegeta n°614',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/11.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Nappa n°613',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/12.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Vegeta n°10',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/13.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Android 16 n°708',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/14.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Gohan n°813',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/15.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Master Roshi n°382',
                'description' => 'Les Pop! Vinyl de Funko sont des figurines de collection produites sous licence officielle qui représentent une énorme gamme de franchises et séries issues de la culture populaire.',
                'price' => 15,
                'quantity' => 2,
                'edition' => 'funko pop',
                'weight' => 525,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/16.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Silent Hill',
                'description' => 'Silent Hill est un jeu vidéo de type survival horror développé par Konami CE Tokyo et édité par Konami en 1999 sur PlayStation. Réputé pour avoir révolutionné le jeu d\'horreur par son approche psychologique de la peur, le titre de Keiichiro Toyama a connu un succès international.',
                'price' => 75,
                'quantity' => 2,
                'edition' => 'Konami',
                'weight' => 347,
                'user_id' => 1,
                'type_id' => 2,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/17.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Lego Harry Potter Years 1-7 PS4, Ps4',
                'description' => 'Décoctions, potions, puzzles, leçons, duels et un jeu amusant plein de sorts, potions, puzzles et amusant pour les personnes de tous âges, familles et amis à jouer ensemble.',
                'price' =>  20,
                'quantity' => 3,
                'edition' => 'Warner Bros',
                'weight' => 120,
                'user_id' => 1,
                'type_id' => 2,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/60.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Super Mario 3D All Stars, Nintendo Switch ',
                'description' => 'Vaporisez des adhésifs ressemblant à de la peinture avec l\'aide de votre ami FLUDD, qui pulvérise de l\'eau dans le jeu Super Mario Sunshine Voyage de planète en planète',
                'price' =>  1200,
                'quantity' => 2,
                'edition' => 'Nintendo Switch',
                'weight' => 73,
                'user_id' => 1,
                'type_id' => 2,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/18.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'TEKKEN 7',
                'description' => 'Rejoignez le dernier chapitre du voyage légendaire du clan Mishima, découvrez la vérité derrière chaque étape de leurs batailles sans fin. vous pouvez faire des duellos incroyables.',
                'price' => 22 ,
                'quantity' => 2,
                'edition' => 'BANDAI NAMCO Studios',
                'weight' => 75,
                'user_id' => 1,
                'type_id' => 2,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/20.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Call Of Duty Black Ops 3 PS3',
                'description' => 'Black Ops 3 emmène les joueurs dans un futur où le nouveau genre militaire Black Ops, qui a émergé grâce à la biotechnologie, joue le rôle principal. Les joueurs seront constamment connectés au réseau de renseignement et aux autres soldats pendant la guerre. ils apprendront les techniques de combat.',
                'price' =>  11,
                'quantity' => 5,
                'edition' => 'Activision',
                'weight' => 68,
                'user_id' => 1,
                'type_id' => 2,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/21.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Game Boy Color - Limited Pokemon Edition - Yellow',
                'description' => 'Tous les articles de cette liste sont en très bon état. tous les jeux fonctionnent et sauvegardent la progression. La console a quelques petites rayures légères sur l\'écran. à peine perceptible. Pokemon Rouge, Bleu, Jaune, Cristal, Argent, Or, Défi de puzzle Pokemon et Jeux de cartes à collectionner Pokemon tous inclus avec des livrets d\'instructions pour chacun et des étuis de jeu en plastique dur assortis.',
                'price' =>  350,
                'quantity' => 1,
                'edition' => 'Nintendo',
                'weight' => 68.03,
                'user_id' => 1,
                'type_id' => 5,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/22.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Game Boy Advance Console - Orange',
                'description' => 'Orange clair Game Boy Advance. Couverture et coque d\'écran flambant neuves.',
                'price' =>  100,
                'quantity' => 1,
                'edition' => 'Nintendo',
                'weight' => 141,
                'user_id' => 1,
                'type_id' => 5,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/23.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Pokemon: Yellow Version - Special Pikachu Edition',
                'description' => 'Si vous n\'avez jamais joué à aucun des jeux Pokémon auparavant, Pokémon Jaune est le meilleur endroit pour commencer. Mais alors que les Pokémaniaques adoreront les nouvelles fonctionnalités du Jaune, les vétérans moins enthousiastes du Rouge et du Bleu ne trouveront peut-être pas les extras aussi spéciaux.',
                'price' =>  75,
                'quantity' => 1,
                'edition' => 'Everyone- Nintendo',
                'weight' => 96,
                'user_id' => 1,
                'type_id' => 2,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/24.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Game Boy Color Super Mario Bros. Deluxe',
                'description' => 'Retrouvez la magie du Super Mario Bros original dans cette exclusivité Game Boy Color. Partez au combat avec Bowser et l\'équipage de Koopa dans une course contre la montre pour sauver la princesse emprisonnée. Profitez de toutes nouvelles options et fonctionnalités bonus. Guidez Mario à travers 8 mondes regorgeant de fleurs secrètes et de toutes sortes de surprises derrière des blocs cassables. Vous pouvez même imprimer des autocollants spéciaux avec l\'imprimante Game Boy. la compétition à 2 joueurs est possible avec le câble Game Link.',
                'price' =>  245,
                'quantity' => 1,
                'edition' => 'Nintendo',
                'weight' => 38,
                'user_id' => 1,
                'type_id' => 2,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/25.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'The Legend of Zelda: Four Swords Adventures - Nintendo Gamecube (Renewed)',
                'description' => 'La Légende de Zelda: Aventures aux Quatre Épées',
                'price' =>  1500,
                'quantity' => 2,
                'edition' => 'GameCube- Everyone',
                'weight' => 90,
                'user_id' => 1,
                'type_id' => 2,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/26.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Pokemon Center Pokémon TCG: XY—Flashfire Sleeved Booster Pack (10 Cards)',
                'description' => 'Contains 10 cards per pack',
                'price' =>  67,
                'quantity' => 2,
                'edition' => 'Pokemon',
                'weight' => 9,
                'user_id' => 1,
                'type_id' => 3,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/28.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'PlayStation 5',
                'description' => 'La PlayStation 5, dernière-née de Sony, offre des graphismes époustouflants et des temps de chargement ultra rapides.',
                'price' => 499,
                'quantity' => 1,
                'edition' => 'Sony',
                'weight' => 4512,
                'user_id' => 1,
                'type_id' => 5,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/30.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Xbox Series X',
                'description' => 'La console la plus puissante de Microsoft à ce jour, la Xbox Series X est le fleuron du jeu de nouvelle génération.',
                'price' => 499,
                'quantity' => 1,
                'edition' => 'Microsoft',
                'weight' => 4441,
                'user_id' => 1,
                'type_id' => 5,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/31.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Nintendo Switch',
                'description' => 'Une console hybride qui peut être utilisée à la maison ou en déplacement.',
                'price' => 299,
                'quantity' => 1,
                'edition' => 'Nintendo',
                'weight' => 413,
                'user_id' => 1,
                'type_id' => 5,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/32.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'PlayStation 4 Pro',
                'description' => 'Version améliorée de la PlayStation 4, offrant des graphismes 4K et une meilleure performance.',
                'price' => 399,
                'quantity' => 1,
                'edition' => 'Sony',
                'weight' => 3300,
                'user_id' => 1,
                'type_id' => 5,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/33.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Xbox One X',
                'description' => 'Version premium de la Xbox One, offrant une résolution en 4K.',
                'price' => 499,
                'quantity' => 1,
                'edition' => '1TB',
                'weight' => 4400,
                'user_id' => 1,
                'type_id' => 5,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/34.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Nintendo Switch Lite',
                'description' => 'Version exclusivement portable de la Nintendo Switch.',
                'price' => 199,
                'quantity' => 1,
                'edition' => 'Nintendo',
                'weight' => 275,
                'user_id' => 1,
                'type_id' => 5,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/35.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'PlayStation 4',
                'description' => 'Console de huitième génération de Sony, précédant la PS5.',
                'price' => 299,
                'quantity' => 1,
                'edition' => 'Sony',
                'weight' => 2804,
                'user_id' => 1,
                'type_id' => 5,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/36.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Super Mario Bros Nes',
                'description' => 'Le jeu de plateforme qui a introduit Mario au monde, sorti sur NES.',
                'price' => 426,
                'quantity' => 1,
                'edition' => 'Original',
                'weight' => 130,
                'user_id' => 1,
                'type_id' => 2,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/37.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'The Legend of Zelda',
                'description' => 'Un jeu d\'aventure épique sur NES mettant en vedette Link dans sa quête pour sauver la princesse Zelda.',
                'price' => 758,
                'quantity' => 1,
                'edition' => 'Original',
                'weight' => 102,
                'user_id' => 1,
                'type_id' => 2,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/38.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Pac-Man',
                'description' => 'Le jeu d\'arcade classique où le joueur contrôle Pac-Man à travers un labyrinthe, mangeant des pac-dots.',
                'price' => 54,
                'quantity' => 1,
                'edition' => 'Original Arcade',
                'weight' => 120,
                'user_id' => 1,
                'type_id' => 2,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/38.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Tetris',
                'description' => 'Jeu de puzzle où les joueurs doivent empiler des blocs géométriques pour former des lignes.',
                'price' => 46,
                'quantity' => 1,
                'edition' => 'Nintendo',
                'weight' => 80,
                'user_id' => 1,
                'type_id' => 2,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/51.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Space Invaders',
                'description' => 'Un des premiers jeux de tir où les joueurs doivent défendre la Terre contre des hordes d\'aliens.',
                'price' => 965,
                'quantity' => 1,
                'edition' => 'Original Arcade',
                'weight' => 102,
                'user_id' => 1,
                'type_id' => 2,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/50.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Dragon Ball Lot premier edition',
                'description' => "L\'histoire de Goku, depuis son enfance jusqu\'à l\'âge adulte, alors qu\'il apprend les arts martiaux et découvre le monde.",
                'price' => 205,
                'quantity' => 1,
                'edition' => 'Kana',
                'weight' => 421,
                'user_id' => 1,
                'type_id' => 4,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/49.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Astro Boy (Tetsuwan Atom)',
                'description' => "Créé par Osamu Tezuka, c\'est l\'histoire d\'un robot garçon doté d\'une intelligence artificielle et d\'une force incroyable.",
                'price' => 150,
                'quantity' => 1,
                'edition' => 'Original',
                'weight' => 412,
                'user_id' => 1,
                'type_id' => 4,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/47.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Maison Ikkoku',
                'description' => "Écrit par Rumiko Takahashi, c\'est une comédie romantique centrée sur les résidents d\'un immeuble d\'appartements et leur concierge.",
                'price' => 45,
                'quantity' => 1,
                'edition' => 'Première édition',
                'weight' => 362,
                'user_id' => 1,
                'type_id' => 4,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/46.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Fist of the North Star (Hokuto no Ken)',
                'description' => "Un manga post-apocalyptique mettant en scène Kenshiro, maître du Hokuto Shinken, dans sa quête de justice.",
                'price' => 84,
                'quantity' => 1,
                'edition' => 'Original',
                'weight' => 420,
                'user_id' => 1,
                'type_id' => 4,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/45.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Figurine Optimus Prime',
                'description' => "Figurine transformable du leader des Autobots, Optimus Prime, issue de la série Transformers des années 80.",
                'price' => 150,
                'quantity' => 1,
                'edition' => 'Original',
                'weight' => 700,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/44.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Figurine He-Man',
                'description' => "Figurine du héros emblématique de la série Maîtres de l\'Univers, He-Man.",
                'price' => 120,
                'quantity' => 1,
                'edition' => 'Original',
                'weight' => 500,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/42.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Figurine Luke Skywalker',
                'description' => "Figurine représentant Luke Skywalker avec son sabre laser, issue de la trilogie originale Star Wars.",
                'price' => 80,
                'quantity' => 1,
                'edition' => 'Original',
                'weight' => 462,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/41.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Figurine G.I. Joe - Snake Eyes',
                'description' => "Figurine de Snake Eyes, membre emblématique de l\'équipe G.I. Joe.",
                'price' => 90,
                'quantity' => 1,
                'edition' => 'Original',
                'weight' => 452,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/43.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
            [
                'name' => 'Figurine Thundercats - Lion-O',
                'description' => "Figurine du leader des Thundercats, Lion-O, avec l\'épée d\'Omens.",
                'price' => 110,
                'quantity' => 1,
                'edition' => 'Original',
                'weight' => 502,
                'user_id' => 1,
                'type_id' => 1,
                'condition' => $faker->randomElement(['Neuf emballage d\'origine', 'Parfait', 'Moyen', 'Mauvais']),
                'image' => 'images/40.jpg',
                'type_transaction' => 'Vente',
                'isAvailable' => true,
                'created_at' => now(),
            ],
        ];
        DB::table('products')->insert($products);
    }
}
